import {Declaration} from '.';
import {Constructor, Main, Macro} from './definitions';

export function compile(
  entry: Main | [Main, Constructor],
  fields: {
    /** Authors of this contract, usually "name <github-link>" */
    authors?: string[];
    /** SPDX license of the contract. */
    license?: 'UNLICENSED' | 'MIT' | string;
    /** Title of the contract. */
    title?: string;
    /** A short description of the contract. */
    description?: string;
  } = {}
): string {
  let macros: Macro[] = Array.isArray(entry) ? entry : [entry];

  let declarations: {[x in Declaration['type']]: string[]} = {
    constant: [],
    error: [],
    event: [],
    function: [],
  };
  let bodies: string[] = [];

  // compile all macros
  while (macros.length !== 0) {
    let macro = macros.pop()!;

    let comp = macro.compile();
    bodies.push(comp.body);
    comp.declarables.forEach(d => {
      if (!d.isDeclared) {
        declarations[d.type].push(d.declare().decl);
      }
    });
    macros.push(...comp.macros.filter(m => !m.isCompiled));
  }

  const headers = [
    fields.title ? `/// @title ${fields.title}` : null,
    fields.license ? `/// @notice SPDX-License-Identifier: ${fields.license}` : null,
    fields.authors ? fields.authors.map(a => `/// @author ${a}`).join('\n') : null,
    fields.description ? `/// @notice ${fields.description}` : null,
    '/// @notice auto-generated by <https://github.com/erhant/thuffs>',
  ];

  const constants = declarations.constant.length
    ? `
////////////////////////////////////////////////////////////////
//                         CONSTANTS                          //
////////////////////////////////////////////////////////////////

${declarations.constant.join('\n')}`
    : null;

  // errors
  const errors = declarations.error.length
    ? `
////////////////////////////////////////////////////////////////
//                           ERRORS                           //
////////////////////////////////////////////////////////////////

${declarations.error.join('\n')}`
    : null;

  // events
  const events = declarations.event.length
    ? `
////////////////////////////////////////////////////////////////
//                           EVENTS                           //
////////////////////////////////////////////////////////////////

${declarations.event.join('\n')}`
    : null;

  // functions
  const functions = declarations.function.length
    ? `
////////////////////////////////////////////////////////////////
//                          FUNCTIONS                         //
////////////////////////////////////////////////////////////////

${declarations.function.join('\n')}`
    : null;

  const macroBodies = `
////////////////////////////////////////////////////////////////
//                            MACROS                          //
////////////////////////////////////////////////////////////////

${bodies.reverse().join('\n\n')}
`;

  return [...headers, constants, errors, events, functions, macroBodies].filter(a => a !== null).join('\n');
}
