import {Body, Declaration} from './common';

export function compile(
  entry: Body | Body[],
  fields: {
    /** Authors of this contract, usually "name <github-link>" */
    authors?: string[];
    /** SPDX license of the contract. */
    license?: string;
    /** Title of the contract. */
    title?: string;
    /** A short description of the contract. */
    comments?: string[];
  } = {}
): string {
  const bodyQueue: Body[] = Array.isArray(entry) ? entry : [entry];
  const declarations: {[x in Declaration['type']]: string[]} = {
    constant: [],
    error: [],
    event: [],
    function: [],
    table: [],
  };
  const bodies: string[] = [];

  while (bodyQueue.length !== 0) {
    const body = bodyQueue.pop()!;

    const comp = body.compile();
    bodies.push(comp.body);
    comp.declarables.forEach(d => {
      if (!d.isDeclared) {
        declarations[d.type].push(d.declare().decl);
      }
    });
    bodyQueue.push(...comp.macros.filter(m => !m.isCompiled));
  }

  const headers = [
    fields.title ? `/// @title ${fields.title}` : null,
    fields.license ? `/// @notice SPDX-License-Identifier: ${fields.license}` : null,
    fields.authors ? fields.authors.map(a => `/// @author ${a}`).join('\n') : null,
    fields.comments ? fields.comments.map(c => `/// @notice ${c}`).join('\n') : null,
    '/// @dev auto-generated by <https://github.com/erhant/thuffs>',
  ];

  const constants = declarations.constant.length
    ? `
////////////////////////////////////////////////////////////////
//                         CONSTANTS                          //
////////////////////////////////////////////////////////////////

${declarations.constant.join('\n')}`
    : null;

  // errors
  const errors = declarations.error.length
    ? `
////////////////////////////////////////////////////////////////
//                           ERRORS                           //
////////////////////////////////////////////////////////////////

${declarations.error.join('\n')}`
    : null;

  // events
  const events = declarations.event.length
    ? `
////////////////////////////////////////////////////////////////
//                           EVENTS                           //
////////////////////////////////////////////////////////////////

${declarations.event.join('\n')}`
    : null;

  // functions
  const functions = declarations.function.length
    ? `
////////////////////////////////////////////////////////////////
//                          FUNCTIONS                         //
////////////////////////////////////////////////////////////////

${declarations.function.join('\n')}`
    : null;

  const macroBodies = `
////////////////////////////////////////////////////////////////
//                            MACROS                          //
////////////////////////////////////////////////////////////////

${bodies.reverse().join('\n\n')}
`;

  return [...headers, constants, errors, events, functions, macroBodies].filter(a => a !== null).join('\n');
}
